stages:
  - lint
  - build
  - test
  - deploy

cache:
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/
    - .yarn

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

build:
  stage: build
  image: node:14@sha256:fe842f5b828c121514d62cbe0ace0927aec4f3130297180c3343e54e7ae97362
  script:
    - &npm-install yarn install --frozen-lockfile --cache-folder .yarn
    - yarn run build
  artifacts:
    paths:
      - ./dist

eslint:
  stage: lint
  image: node:14@sha256:fe842f5b828c121514d62cbe0ace0927aec4f3130297180c3343e54e7ae97362
  script:
    - *npm-install
    - yarn run lint:eslint

prettier:
  stage: lint
  image: node:14@sha256:fe842f5b828c121514d62cbe0ace0927aec4f3130297180c3343e54e7ae97362
  script:
    - *npm-install
    - yarn run lint:prettier

ts-check:
  stage: lint
  image: node:14@sha256:fe842f5b828c121514d62cbe0ace0927aec4f3130297180c3343e54e7ae97362
  script:
    - *npm-install
    - yarn run ts-check
